collections:
  # infra.ee_utilities - contains ee_builder, to run ansible-builder to built EE image from ansible playbook
  # - name: infra.ee_utilities
  # update to latest version
  - name: infra.aap_configuration
    version: 3.1.0
