---
# This is just a workaround.
#
# Setting environ variables
# ANSIBLE_GALAXY_SERVER_LIST
# ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL
# ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL
# ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_TOKEN
# should be enough to make 'ansible-galaxy collection verify ansible.controller' happy.
# But it still fails with
#   [WARNING]: Skipping Galaxy server https://console.redhat.com/api/automation-hub/content/published/. Got an unexpected error when getting available versions
#   of collection ansible.controller: HTTP Error 400: Bad Request
#   ERROR! Unexpected Exception, this is probably a bug: HTTP Error 400: Bad Request
# Maybe ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_TOKEN needs a diffrent format.
#
# For now, put all this into ansible.cfg.
# It will not be used by this already-running ansible-playbook.
# But it will be used by 'ansible-galaxy collection verify'.

- name: Create ansible.cfg to allow access to automation hub
  ansible.builtin.copy:
    dest: ansible.cfg
    mode: 0644
    content: |
      [galaxy]
      server_list = automation_hub
      [galaxy_server.automation_hub]
      url=https://console.redhat.com/api/automation-hub/content/published/
      auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
      token={{ ansible_galaxy_server_automation_hub_auth_token }}
      # [galaxy_server.release_galaxy]
      # url=https://galaxy.ansible.com/
